/*
 * (C) Copyright IBM Corp. 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.schematics.v1.model;

import java.util.Date;
import java.util.List;

import com.google.gson.annotations.SerializedName;
import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * Output files from the Job record.
 */
public class JobFileData extends GenericModel {

  /**
   * The type of output file generated by the Job.
   */
  public interface FileType {
    /** state_file. */
    String STATE_FILE = "state_file";
    /** plan_json. */
    String PLAN_JSON = "plan_json";
    /** quote_json. */
    String QUOTE_JSON = "quote_json";
    /** draft_plan_json. */
    String DRAFT_PLAN_JSON = "draft_plan_json";
    /** git_files. */
    String GIT_FILES = "git_files";
    /** cost_json. */
    String COST_JSON = "cost_json";
    /** log_insights_file. */
    String LOG_INSIGHTS_FILE = "log_insights_file";
  }

  @SerializedName("job_id")
  protected String jobId;
  @SerializedName("job_name")
  protected String jobName;
  protected List<JobFileDataSummary> summary;
  @SerializedName("file_type")
  protected String fileType;
  @SerializedName("file_content")
  protected String fileContent;
  @SerializedName("additional_files")
  protected List<JobFileContent> additionalFiles;
  @SerializedName("updated_at")
  protected Date updatedAt;

  protected JobFileData() { }

  /**
   * Gets the jobId.
   *
   * Job Id.
   *
   * @return the jobId
   */
  public String getJobId() {
    return jobId;
  }

  /**
   * Gets the jobName.
   *
   * Job name, uniquely derived from the related Workspace and Action.
   *
   * @return the jobName
   */
  public String getJobName() {
    return jobName;
  }

  /**
   * Gets the summary.
   *
   * Summary metadata in the output files.
   *
   * @return the summary
   */
  public List<JobFileDataSummary> getSummary() {
    return summary;
  }

  /**
   * Gets the fileType.
   *
   * The type of output file generated by the Job.
   *
   * @return the fileType
   */
  public String getFileType() {
    return fileType;
  }

  /**
   * Gets the fileContent.
   *
   * Content of the file, generated by the job.
   *
   * @return the fileContent
   */
  public String getFileContent() {
    return fileContent;
  }

  /**
   * Gets the additionalFiles.
   *
   * Content of the additional files, generated by the child job.
   *
   * @return the additionalFiles
   */
  public List<JobFileContent> getAdditionalFiles() {
    return additionalFiles;
  }

  /**
   * Gets the updatedAt.
   *
   * Job file updation timestamp.
   *
   * @return the updatedAt
   */
  public Date getUpdatedAt() {
    return updatedAt;
  }
}

