/*
 * (C) Copyright IBM Corp. 2021.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.schematics.v1.model;

import java.util.Date;

import com.google.gson.annotations.SerializedName;
import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * Job Log details.
 */
public class JobLog extends GenericModel {

  /**
   * Format of the Log text.
   */
  public interface Format {
    /** json. */
    String JSON = "json";
    /** html. */
    String HTML = "html";
    /** markdown. */
    String MARKDOWN = "markdown";
    /** rtf. */
    String RTF = "rtf";
  }

  @SerializedName("job_id")
  protected String jobId;
  @SerializedName("job_name")
  protected String jobName;
  @SerializedName("log_summary")
  protected JobLogSummary logSummary;
  protected String format;
  protected byte[] details;
  @SerializedName("updated_at")
  protected Date updatedAt;

  /**
   * Gets the jobId.
   *
   * Job Id.
   *
   * @return the jobId
   */
  public String getJobId() {
    return jobId;
  }

  /**
   * Gets the jobName.
   *
   * Job name, uniquely derived from the related Workspace, Action or Controls.
   *
   * @return the jobName
   */
  public String getJobName() {
    return jobName;
  }

  /**
   * Gets the logSummary.
   *
   * Job log summary record.
   *
   * @return the logSummary
   */
  public JobLogSummary getLogSummary() {
    return logSummary;
  }

  /**
   * Gets the format.
   *
   * Format of the Log text.
   *
   * @return the format
   */
  public String getFormat() {
    return format;
  }

  /**
   * Gets the details.
   *
   * Log text, generated by the Job.
   *
   * @return the details
   */
  public byte[] getDetails() {
    return details;
  }

  /**
   * Gets the updatedAt.
   *
   * Job status updation timestamp.
   *
   * @return the updatedAt
   */
  public Date getUpdatedAt() {
    return updatedAt;
  }
}

